# Generated by Django 5.0.7 on 2024-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
